name: Autoassign issue

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  issue_assign:
    name: "Call `Autoassign issue` shared workflow"
    uses: cumbucadev/shared-workflows/.github/workflows/autoassign-issue-v1.yml@main
